### PR TITLE
feat: passthrough target option

### PR DESCRIPTION
**Pull request by limwa**
This PR allows users of the action to set a target stage for the build.

### CODE REVIEW

**Review by LuisDuarte1 — APPROVED** [review]
LGTM :rocket:

**Review by Naapperas — APPROVED** [review]
Worried that passing a `null` target to the docker action might cause some problems. I went to the action's source code and it should not pose a problem but this needs to be tested.

**Comment by limwa** [comment]
I copied the properties' definition from the build and push action, so it should be okay.

**Comment by Naapperas** [comment]
@limwa can you do a small chore PR to update the README (it still mentions `v1`) and the CHANGELOG?

And ideally release a new patch/minor

**Comment by limwa** [comment]
> @limwa can you do a small chore PR to update the README (it still mentions `v1`) and the CHANGELOG?
> 
> And ideally release a new patch/minor

Done!

**Pull request merged**
